import { LRUCache } from "lru-cache";

import { completeChat, hasLlmKeyConfigured } from "../ai/llm.js";

import { SuggestionKind } from "./suggestion-kind.js";
import { SuggestionPair, SuggestedBook } from "./suggestion-pair.js";

// AI-generated suggestions for the app's typewriter placeholders: evocative vocabulary words,
// well-known books (structured as { title, author, year }), and evocative sentences per
// language. Generated by an LLM on Groq's free tier (see llm.ts).
// Without GROQ_API_KEY the feature is off and callers get empty arrays.
//
// Cached in memory, one entry per language, and each entry expires after
// SUGGESTIONS_CACHE_TTL_MS (default 15 min). The cache exists to avoid re-spending Groq
// quota on repeat requests for the same language — Groq's free tier is limited mostly by
// tokens per minute, and one /suggestions request already fires three completions at once
// (words/books/sentences).
//
// analyze.ts's cache has no Time To Live (TTL), since a sentence's explanation never changes. 
// This one does, because "new vocabulary" is meant to actually get replaced eventually.

/**
 * Builds the prompt asking the model for a list of vocabulary words in `language`.
 *
 * @param {string} language The ISO 639 language code to generate words for.
 * @returns {string} The full prompt text.
 * 
 */
function wordsPrompt(language: string): string {
  return [
    `Generate 80 vocabulary words in the language with ISO 639 code "${language}".`,
    "Pick words an avid reader would love to save: evocative, precise, or",
    "beautiful — a mix of moderately advanced and rare-but-real words.",
    "Rules: lowercase; single words only (no phrases); no proper nouns; no duplicates.",
    'Respond with ONLY a JSON array of strings, like ["word","word"].',
  ].join(" ");
}

/**
 * Builds the prompt asking the model for a list of well-known books in `language`,
 * each with its title, author and original publication year, as structured JSON objects.
 *
 * @param {string} language The ISO 639 language code to generate books for.
 * @returns {string} The full prompt text.
 *
 */
function booksPrompt(language: string): string {
  return [
    `List 40 real, well-known books that readers in the "${language}" language market recognize.`,
    "Mostly classics and famous novels; use the title as published in that",
    "language where that form is better known, otherwise the original title.",
    "Rules: real books only; use the real author's name and the original publication year; no duplicates.",
    "Respond with ONLY a JSON array of objects, each shaped exactly as",
    '{"title":"...","author":"...","year":"YYYY"}.',
  ].join(" ");
}

/**
 * Builds the prompt asking the model for a list of evocative sentences in `language`.
 *
 * @param {string} language The ISO 639 language code to generate sentences for.
 * @returns {string} The full prompt text.
 * 
 */
function sentencesPrompt(language: string): string {
  return [
    `Generate 3 short, evocative sentences in the language with ISO 639 code "${language}".`,
    "Pick sentences an avid reader would love to save: evocative, precise, or",
    "beautiful — a mix of moderately advanced and rare-but-real sentences.",
    "Rules: single sentences only (no paragraphs); no proper nouns; no duplicates.",
    'Respond with ONLY a JSON array of strings, like ["sentence.","sentence."].',
  ].join(" ");
}

// Matches sanitizeWord's spirit (words.ts): letters/marks with inner apostrophes
// or hyphens — single words only, so no spaces.
const WORD_REGEX = /^[\p{L}\p{M}][\p{L}\p{M}'-]*$/u;

/**
 * Tolerantly extracts a JSON array out of the model's raw text reply: finds the
 * first `[` and the last `]`, slices between them, and parses that substring —
 * so a ```json fence or a sentence of preamble doesn't prevent parsing.
 *
 * @param {string} text The raw text to search for a JSON array.
 * @returns {unknown} The parsed value, or `null` if none was found or parsing failed.
 * 
 */
function extractJsonArray(text: string): unknown {
  const start = text.indexOf("[");
  const end = text.lastIndexOf("]");
  if (start === -1 || end <= start) {
    return null;
  }
  try {
    return JSON.parse(text.slice(start, end + 1));
  } catch {
    return null;
  }
}

/**
 * Pulls a clean string array out of the model's reply: tolerate ```json fences
 * and surrounding prose, then keep only sane entries.
 *
 * @param {string} text The model's raw text reply.
 * @param {SuggestionKind} kind Which list this is — controls the length cap and, for `"words"`, the word-shape check.
 * @returns {string[]} The cleaned, deduplicated suggestion strings.
 *
 */
export function parseSuggestionList(text: string, kind: SuggestionKind): string[] {
  const parsed = extractJsonArray(text);
  if (!Array.isArray(parsed)) {
    return [];
  }

  // words are single words; sentences run longer.
  const maxLength = kind === "words" ? 60 : 120;
  const seen = new Set<string>();
  const items: string[] = [];
  for (const raw of parsed) {
    if (typeof raw !== "string") {
      continue;
    }
    let item = raw.replace(/\s+/g, " ").trim();
    if (kind === "words") {
      item = item.toLowerCase();
      if (!WORD_REGEX.test(item)) {
        continue;
      }
    }
    if (!item || item.length > maxLength) {
      continue;
    }
    if (item.includes("://") || item.includes("http") || item.includes("@")) {
      continue;
    }
    const key = item.toLowerCase();
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    items.push(item);
  }
  return items;
}

const MAX_BOOK_FIELD_LENGTH = 100;
const MAX_BOOKS = 40;

/**
 * Pulls a clean, structured book list out of the model's reply: tolerate ```json
 * fences and surrounding prose, then keep only well-shaped `{ title, author, year }`
 * entries — dropping anything malformed rather than including it half-filled.
 *
 * @param {string} text The model's raw text reply.
 * @returns {SuggestedBook[]} The cleaned, deduplicated (by title) suggestions, capped at 40.
 *
 */
export function parseBookList(text: string): SuggestedBook[] {
  const parsed = extractJsonArray(text);
  if (!Array.isArray(parsed)) {
    return [];
  }

  const seen = new Set<string>();
  const items: SuggestedBook[] = [];
  for (const raw of parsed) {
    if (typeof raw !== "object" || raw === null) {
      continue;
    }
    const { title: rawTitle, author: rawAuthor, year: rawYear } = raw as Record<string, unknown>;
    if (typeof rawTitle !== "string" || typeof rawAuthor !== "string") {
      continue;
    }
    const title = rawTitle.replace(/\s+/g, " ").trim();
    const author = rawAuthor.replace(/\s+/g, " ").trim();
    // The model sometimes gives the year as a number rather than a string.
    const year = String(rawYear ?? "").trim();
    if (!title || !author || !year) {
      continue;
    }
    if (title.length > MAX_BOOK_FIELD_LENGTH || author.length > MAX_BOOK_FIELD_LENGTH || year.length > 20) {
      continue;
    }
    if ([title, author].some((v) => v.includes("://") || v.includes("http") || v.includes("@"))) {
      continue;
    }
    const key = title.toLowerCase();
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    items.push({ title, author, year });
    if (items.length >= MAX_BOOKS) {
      break;
    }
  }
  return items;
}

// Sized generously above what each prompt realistically needs. A truncated reply breaks
// extractJsonArray's parsing and silently returns an empty list — worse than just spending
// a few hundred extra tokens. All three together (3500) plus input tokens still stay well
// under Groq's free-tier 6,000 TPM limit — unlike the old flat 4000-per-call default, which
// summed to 12,000 across the three.
const WORDS_MAX_TOKENS = 1000;
const BOOKS_MAX_TOKENS = 2000;
const SENTENCES_MAX_TOKENS = 500;

const SUGGESTIONS_CACHE_TTL_MS = Number(process.env.SUGGESTIONS_CACHE_TTL_MS) || 900_000;

// In-memory only — resets on server restart. Keyed by language, 
// never caches an empty/failed result. 
// `max` is just extra hardening: `language` is already regex-validated (`^[a-z]{2,3}$`) 
// before it gets here, but this caps memory in case many different fake-but-valid codes get requested.
const cache = new LRUCache<string, SuggestionPair>({ ttl: SUGGESTIONS_CACHE_TTL_MS, max: 100 });

/**
 * Checks whether a suggestion pair for this language is already cached, without triggering
 * a live call if it isn't. Used by index.ts to set the `X-Cache` response header.
 *
 * @param {string} language The ISO 639 language code to check.
 * @returns {boolean} `true` if a cached (and unexpired) result exists for this language.
 *
 */
export function isSuggestionPairCached(language: string): boolean {
  return cache.has(language);
}

/**
 * Fetches suggestion lists (words, books and sentences) for a language, serving a cached
 * result when one exists and hasn't expired, otherwise calling the model live for each.
 *
 * @param {string} language The ISO 639 language code to fetch suggestions for.
 * @returns {Promise<SuggestionPair>} Both lists, each empty `[]` if the LLM is disabled or generation failed.
 *
 */
export async function getSuggestionPair(language: string): Promise<SuggestionPair> {
  // Check if there is a saved result already with the language key.
  // If there is, return it.
  const cachedLanguage = cache.get(language);
  if (cachedLanguage !== undefined) {
    return cachedLanguage;
  }

  if (!hasLlmKeyConfigured()) {
    return { words: [], books: [], sentences: [] };
  }

  const [wordsText, booksText, sentencesText] = await Promise.all([
    completeChat(wordsPrompt(language), { maxTokens: WORDS_MAX_TOKENS }),
    completeChat(booksPrompt(language), { maxTokens: BOOKS_MAX_TOKENS }),
    completeChat(sentencesPrompt(language), { maxTokens: SENTENCES_MAX_TOKENS }),
  ]);

  const suggestionPair: SuggestionPair = {
    words: parseSuggestionList(wordsText, "words"),
    books: parseBookList(booksText),
    sentences: parseSuggestionList(sentencesText, "sentences"),
  };

  // Never cache a failed/empty generation — a transient Groq error (e.g. a 429 status)
  // Only set it if a result is given
  if (suggestionPair.words.length > 0 || suggestionPair.books.length > 0 || suggestionPair.sentences.length > 0) {
    cache.set(language, suggestionPair);
  }

  return suggestionPair;
}
