import { completeChat, hasLlmKeyConfigured } from "../ai/llm.js";

import { SuggestionKind } from "./suggestion-kind.js";
import { SuggestionPair, SuggestedTitle } from "./suggestion-pair.js";

// AI-generated suggestions for the app's typewriter placeholders: evocative vocabulary words,
// well-known book titles (structured as { title, author, year }), and evocative sentences per
// language. Generated by an LLM on Groq's free tier (see llm.ts). Kept deliberately simple — no
// cache, no TTL — so every /suggestions request calls the model live. Without GROQ_API_KEY the
// feature is off and callers get empty arrays.

/**
 * Builds the prompt asking the model for a list of vocabulary words in `language`.
 *
 * @param {string} language The ISO 639 language code to generate words for.
 * @returns {string} The full prompt text.
 * 
 */
function wordsPrompt(language: string): string {
  return [
    `Generate 80 vocabulary words in the language with ISO 639 code "${language}".`,
    "Pick words an avid reader would love to save: evocative, precise, or",
    "beautiful — a mix of moderately advanced and rare-but-real words.",
    "Rules: lowercase; single words only (no phrases); no proper nouns; no duplicates.",
    'Respond with ONLY a JSON array of strings, like ["word","word"].',
  ].join(" ");
}

/**
 * Builds the prompt asking the model for a list of well-known book titles in `language`,
 * each with its author and original publication year, as structured JSON objects.
 *
 * @param {string} language The ISO 639 language code to generate titles for.
 * @returns {string} The full prompt text.
 *
 */
function titlesPrompt(language: string): string {
  return [
    `List 40 real, well-known book titles that readers in the "${language}" language market recognize.`,
    "Mostly classics and famous novels; use the title as published in that",
    "language where that form is better known, otherwise the original title.",
    "Rules: real books only; use the real author's name and the original publication year; no duplicates.",
    "Respond with ONLY a JSON array of objects, each shaped exactly as",
    '{"title":"...","author":"...","year":"YYYY"}.',
  ].join(" ");
}

/**
 * Builds the prompt asking the model for a list of evocative sentences in `language`.
 *
 * @param {string} language The ISO 639 language code to generate sentences for.
 * @returns {string} The full prompt text.
 * 
 */
function sentencesPrompt(language: string): string {
  return [
    `Generate 3 short, evocative sentences in the language with ISO 639 code "${language}".`,
    "Pick sentences an avid reader would love to save: evocative, precise, or",
    "beautiful — a mix of moderately advanced and rare-but-real sentences.",
    "Rules: single sentences only (no paragraphs); no proper nouns; no duplicates.",
    'Respond with ONLY a JSON array of strings, like ["sentence.","sentence."].',
  ].join(" ");
}

// Matches sanitizeWord's spirit (words.ts): letters/marks with inner apostrophes
// or hyphens — single words only, so no spaces.
const WORD_REGEX = /^[\p{L}\p{M}][\p{L}\p{M}'-]*$/u;

/**
 * Tolerantly extracts a JSON array out of the model's raw text reply: finds the
 * first `[` and the last `]`, slices between them, and parses that substring —
 * so a ```json fence or a sentence of preamble doesn't prevent parsing.
 *
 * @param {string} text The raw text to search for a JSON array.
 * @returns {unknown} The parsed value, or `null` if none was found or parsing failed.
 * 
 */
function extractJsonArray(text: string): unknown {
  const start = text.indexOf("[");
  const end = text.lastIndexOf("]");
  if (start === -1 || end <= start) {
    return null;
  }
  try {
    return JSON.parse(text.slice(start, end + 1));
  } catch {
    return null;
  }
}

/**
 * Pulls a clean string array out of the model's reply: tolerate ```json fences
 * and surrounding prose, then keep only sane entries.
 *
 * @param {string} text The model's raw text reply.
 * @param {SuggestionKind} kind Which list this is — controls the length cap and, for `"words"`, the word-shape check.
 * @returns {string[]} The cleaned, deduplicated suggestion strings.
 *
 */
export function parseSuggestionList(text: string, kind: SuggestionKind): string[] {
  const parsed = extractJsonArray(text);
  if (!Array.isArray(parsed)) {
    return [];
  }

  // words are single words; sentences run longer.
  const maxLength = kind === "words" ? 60 : 120;
  const seen = new Set<string>();
  const items: string[] = [];
  for (const raw of parsed) {
    if (typeof raw !== "string") {
      continue;
    }
    let item = raw.replace(/\s+/g, " ").trim();
    if (kind === "words") {
      item = item.toLowerCase();
      if (!WORD_REGEX.test(item)) {
        continue;
      }
    }
    if (!item || item.length > maxLength) {
      continue;
    }
    if (item.includes("://") || item.includes("http") || item.includes("@")) {
      continue;
    }
    const key = item.toLowerCase();
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    items.push(item);
  }
  return items;
}

const MAX_TITLE_FIELD_LENGTH = 100;
const MAX_TITLES = 40;

/**
 * Pulls a clean, structured title list out of the model's reply: tolerate ```json
 * fences and surrounding prose, then keep only well-shaped `{ title, author, year }`
 * entries — dropping anything malformed rather than including it half-filled.
 *
 * @param {string} text The model's raw text reply.
 * @returns {SuggestedTitle[]} The cleaned, deduplicated (by title) suggestions, capped at 40.
 *
 */
export function parseTitleList(text: string): SuggestedTitle[] {
  const parsed = extractJsonArray(text);
  if (!Array.isArray(parsed)) {
    return [];
  }

  const seen = new Set<string>();
  const items: SuggestedTitle[] = [];
  for (const raw of parsed) {
    if (typeof raw !== "object" || raw === null) {
      continue;
    }
    const { title: rawTitle, author: rawAuthor, year: rawYear } = raw as Record<string, unknown>;
    if (typeof rawTitle !== "string" || typeof rawAuthor !== "string") {
      continue;
    }
    const title = rawTitle.replace(/\s+/g, " ").trim();
    const author = rawAuthor.replace(/\s+/g, " ").trim();
    // The model sometimes gives the year as a number rather than a string.
    const year = String(rawYear ?? "").trim();
    if (!title || !author || !year) {
      continue;
    }
    if (title.length > MAX_TITLE_FIELD_LENGTH || author.length > MAX_TITLE_FIELD_LENGTH || year.length > 20) {
      continue;
    }
    if ([title, author].some((v) => v.includes("://") || v.includes("http") || v.includes("@"))) {
      continue;
    }
    const key = title.toLowerCase();
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    items.push({ title, author, year });
    if (items.length >= MAX_TITLES) {
      break;
    }
  }
  return items;
}

/**
 * Fetches both suggestion lists (words and titles) for a language, calling the model live for
 * each — no caching.
 *
 * @param {string} language The ISO 639 language code to fetch suggestions for.
 * @returns {Promise<SuggestionPair>} Both lists, each empty `[]` if the LLM is disabled or generation failed.
 *
 */
export async function getSuggestionPair(language: string): Promise<SuggestionPair> {
  if (!hasLlmKeyConfigured()) {
    return { words: [], titles: [], sentences: [] };
  }

  const [wordsText, titlesText, sentencesText] = await Promise.all([
    completeChat(wordsPrompt(language)),
    completeChat(titlesPrompt(language)),
    completeChat(sentencesPrompt(language)),
  ]);

  return {
    words: parseSuggestionList(wordsText, "words"),
    titles: parseTitleList(titlesText),
    sentences: parseSuggestionList(sentencesText, "sentences"),
  };
}
