import { completeChat, hasLlmKeyConfigured } from "./llm.js";

// AI-generated plain-language sentence explanations, for the app's "Analyze
// a sentence" screen. Generated by an LLM on Groq's free tier (see llm.ts).
// Kept deliberately simple — no cache, no TTL, no rate limit — so every
// /analyze request calls the model live. Without GROQ_API_KEY the feature is
// off and callers get null.

/**
 * Builds the prompt asking the model to explain a sentence in plain language.
 *
 * @param {string} sentence The sentence to explain.
 * @param {string} language The ISO 639 language code to respond in.
 * @returns {string} The full prompt text.
 *
 */
function analysisPrompt(sentence: string, language: string): string {
  return [
    "Explain, in plain language, what the following sentence means.",
    `Respond in the language with ISO 639 code "${language}".`,
    "Respond with ONLY the explanation — no preamble, no quotes.",
    `Sentence: "${sentence}"`,
  ].join(" ");
}

/**
 * Asks the model to explain a sentence in plain language, calling it live —
 * no caching.
 *
 * @param {string} sentence The sentence to explain.
 * @param {string} language The ISO 639 language code to respond in.
 * @returns {Promise<string | null>} The explanation, or `null` if the LLM is disabled or the reply was empty.
 * 
 */
export async function analyzeSentence(sentence: string, language: string): Promise<string | null> {
  if (!hasLlmKeyConfigured()) {
    return null;
  }

  const reply = await completeChat(analysisPrompt(sentence, language));
  const sentenceMeaning = reply.trim();
  return sentenceMeaning.length > 0 ? sentenceMeaning : null;
}
